SonarSource/sonarlint-vscode

.gitignore
.travis.yml
.vscodeignore
gulpfile.js
package-lock.json
package.json
src/__tests__/util.test.ts
src/extension.ts
src/util.ts
tsconfig.json

This is a first experiment at writing tests with Jest and feeding coverage into SQ.
Test runners had trouble with resolution of some modules (e.g `vscode`), so after struggling with configuration I chose to instead extract unit-testable bits of code and cover them with unit tests.
We'll probably have to dig further to write proper ITs for the actual `extension.ts`, e.g using the extension test runner.

Experiment with coverage on TS files

---

scripts/prepare.js
src/extension.ts

a2745cbbab0b46a25088d66d5038f2829aef1d69 introduced a regression: since the standard streams of the forked process were not consumed, the buffer got full on language server side and hung analyses.
This new version unconditionally attaches stream consumers, then only logs conditionally.

Fix language server freeze after a few analyses

---

package.json
scripts/prepare.js
src/extension.ts

Client side of SLCORE-244, using dedicated command to trigger a refresh of diagnostics after an update to rule configuration.

SLCORE-244 Trigger diagnostics refresh on rules configuration change

---

.vscode/launch.json
package-lock.json
package.json
src/commands.ts
src/extension.ts
src/requirements.ts
test/samples/.vscode/settings.json
test/suite/extension.test.ts
test/suite/requirements.test.ts

Largely inspired from https://github.com/redhat-developer/vscode-java/commit/6bccceab4eda659d03c149daf17a686f85d70158#diff-baff02b04010a735985f63100efb9fc2
- display detected path
- check if java home ends with `bin`
- opens settings if sonarlint.ls.javaHome preference is invalid

Improve Java home detection

---

src/extension.ts

Pending SLCORE update, this passes the expected value to the telemetry client.

SLVSCODE-76 Add IDE version in telemetry

---

package.json

when https://github.com/SonarSource/sonarlint-vscode/pull/6 was merged, there was a dependency to typescript
https://github.com/SonarSource/sonarlint-vscode/blob/54fec88c8c24a2fde12170b80df956be8663dc57/src/extension.ts#L145
but now dependency is `vscode.typescript-language-features` https://github.com/SonarSource/sonarlint-vscode/blob/b61bc9ad5bb5acda481dce3a8bb59448167aaa93/src/extension.ts#L161
Also use `extensionDependencies` instead of `extensionDependency` which is the appropriate name
> Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-vscode/blob/master/contributing.md).
FYI this link is invalid
And please ensure your pull request adheres to the following guidelines:

fix(dependency): Use correct dependency

---

scripts/dependencies.json
src/extension.ts
src/protocol.ts

See [matching changes on LS](https://github.com/SonarSource/sonarlint-language-server/pull/133)

SLVSCODE-276 Check files are open in an editor before triggering analysis

---

dogfood/.vscodeignore

Currently, the dogfooding extension will contain the `.idea` folder if working with JetBrains WebStorm, this PR removes it.
Baby steps, you know ^^

NO-JIRA: Don't package IDEA folder into dogfood

---

its/src/test/javaSuite/java.test.ts
test/runTest.ts
test/samples/sample-for-bindings/.vscode/settings.json
test/samples/samples.code-workspace
test/suite/autobinding.test.ts
test/suite/bindings.test.ts
test/suite/connections.test.ts
test/suite/util.test.ts

Note to reviewers: this does not use the updated SLCORE with additional logs just yet, but it does seem to fix the issues we had previously with cross-test interactions.

Use a multi-folder workspace to restrict binding changes to a single folder

---

src/connected/autobinding.ts
src/extension.ts
test/suite/autobinding.test.ts

This is a first version for SLVSCODE-718 that sends all JSON files from the `.sonarlint` folder without any special case for .Net solutions (as discussed recently).

SLVSCODE-718 Send .sonarlint/*.json files to autobinding facility

---

src/connected/connections.ts
src/lsp/client.ts
src/lsp/protocol.ts
test/suite/connections.test.ts

With my modifications, users should no longer see a similar `<project not found>` message in the SonarLint Connected Mode view.
Unfortunately, they will still not be able to find their project in the list when setting up binding. As a workaround, they can always define the binding setting manually under project/.vscode/settings.json, or also use a [shared binding configuration](https://docs.sonarsource.com/sonarlint/vs-code/team-features/connected-mode/#sharing-your-setup).

SLLS-234 get project names by key

---

.github/workflows/credcheck.yml
.github/workflows/release.yml

* Retrieve secrets from Hashicorp Vault instead of the one stored in GitHub repository
That way the new values are used/updated in Vault.
It should resolve issues of [release](https://github.com/SonarSource/sonarlint-vscode/actions/runs/9349453145) 
* I triggered credcheck.yml on this same branch https://github.com/SonarSource/sonarlint-vscode/actions/runs/9369027317

BUILD-5219 use Hashicorp Vault to retrieve secrets

---

src/connected/connectionsetup.ts

[SLVSCODE-834](https://sonarsource.atlassian.net/browse/SLVSCODE-834)
It is amazing how many hidden problems this was causing 🥲 
[SLVSCODE-834]: https://sonarsource.atlassian.net/browse/SLVSCODE-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-834 store SonarCloud tokens properly

---

src/connected/automaticConnectionCancellationError.ts
src/connected/connectionsetup.ts

[SLLS-226](https://sonarsource.atlassian.net/browse/SLLS-226)
We should cancel the automatic Connection setup if
- User explicitly cancels it
- User decides to open Connected Mode docs
- We default back to old SonarQube setup (when we don't have access to the token immediately)
Throwing cancellation exception from the client and returning `null` to the Language Server will result in unused tokens being revoked immediately.
[SLLS-226]: https://sonarsource.atlassian.net/browse/SLLS-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLLS-226 properly cancel automatic Connection setup

---

scripts/dependencies.json
src/util/showMessage.ts

[SLVSCODE-738](https://sonarsource.atlassian.net/browse/SLVSCODE-738)
[SLVSCODE-738]: https://sonarsource.atlassian.net/browse/SLVSCODE-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-738 show correct default values and setting for actual value in SSL dialog

---

.github/actions/ovsx-publish/main.js
.github/workflows/release.yml

[SLVSCODE-870](https://sonarsource.atlassian.net/browse/SLVSCODE-870)
[SLVSCODE-870]: https://sonarsource.atlassian.net/browse/SLVSCODE-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-870 Fix silent failure of deployment to OpenVSX

---

src/connected/autobinding.ts

Cause of the problem: 🥲 
Fix has been tested on the Windows VM and it works.

SLVSCODE-880 make sure listFilesInFolder returns on Windows

---

.cirrus.star
.cirrus.yml

[SLVSCODE-896](https://sonarsource.atlassian.net/browse/SLVSCODE-896)
1. Update cirrus-module v2 to v3.
2. Do not call the deprecated AWS feature method parameters `subnet_id`.
3. It is recommended to not use `ec2_instance` or `eks_container` root keys.
[SLVSCODE-896]: https://sonarsource.atlassian.net/browse/SLVSCODE-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-896 Migrate deprecated cirrus-module v2 to v3

---

scripts/dependencies.json
src/extension.ts
src/lsp/protocol.ts

[SLVSCODE-877](https://sonarsource.atlassian.net/browse/SLVSCODE-877)
SLLS counterpart is [here](https://github.com/SonarSource/sonarlint-language-server/pull/414)
[SLVSCODE-877]: https://sonarsource.atlassian.net/browse/SLVSCODE-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-877 do not analyze files not open in editor

---

CHANGELOG.md
NOTICE.txt
scripts/dependencies.json

[SLVSCODE-950](https://sonarsource.atlassian.net/browse/SLVSCODE-950)
[SLVSCODE-950]: https://sonarsource.atlassian.net/browse/SLVSCODE-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-950 Update JS analyzer

---

.cirrus/Dockerfile

[SLVSCODE-963](https://sonarsource.atlassian.net/browse/SLVSCODE-963)
Part of SLVSCODE-960
[SLVSCODE-963]: https://sonarsource.atlassian.net/browse/SLVSCODE-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-963 Start depending on dotent 8 instead of 7 in ci image

---

scripts/dependencies.json
src/connected/connectionsetup.ts
src/help/constants.ts
src/lsp/server.ts
webview-ui/connectionsetup.js

[SLVSCODE-984](https://sonarsource.atlassian.net/browse/SLVSCODE-984)
[SLVSCODE-984]: https://sonarsource.atlassian.net/browse/SLVSCODE-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-984 adjust wording about free editions

---

scripts/dependencies.json
src/extension.ts
src/hotspot/hotspotsTreeDataProvider.ts
src/lsp/protocol.ts
src/util/util.ts

Before
After
[SLVSCODE-966](https://sonarsource.atlassian.net/browse/SLVSCODE-966)
[SLVSCODE-966]: https://sonarsource.atlassian.net/browse/SLVSCODE-966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-966 improve UX with taint vulnerabilities on file change

---

CHANGELOG.md
scripts/dependencies.json

Part of SLVSCODE-967
SLVSCODE-980
SLVSCODE-979
SLVSCODE-976
SLVSCODE-974
SLVSCODE-971

SLVSCODE-986 4.15 analyzer updates

---

CHANGELOG.md
README.md
package.json
src/newcode/newCodeDefinitionService.ts

[SLVSCODE-1009](https://sonarsource.atlassian.net/browse/SLVSCODE-1009)
Part of the rebranding efforts necessitates the update of the URL structure on the Docs website. 
This change reflects part of that update.
A redirect has been added to address links from outside the product.
[SLVSCODE-1009]: https://sonarsource.atlassian.net/browse/SLVSCODE-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-1009 URL slug rebranding update

---

.cirrus.yml
its/userdir/User/settings.json
package-lock.json
package.json
src/extension.ts
src/lsp/server.ts
src/monitoring/dogfooding.ts
src/monitoring/monitoring.ts
test/suite/connectionsetup.test.ts
test/userdir/User/settings.json
webpack.config.js

SLVSCODE-951 Enable monitoring of extension with Sentry

---

src/lsp/protocol.ts
test/suite/hotspots.test.ts

[SLVSCODE-1029](https://sonarsource.atlassian.net/browse/SLVSCODE-1029)
[SLVSCODE-1029]: https://sonarsource.atlassian.net/browse/SLVSCODE-1029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-1029 fix order in HotspotResolution enum

---

package.json

[SLVSCODE-721](https://sonarsource.atlassian.net/browse/SLVSCODE-721)
The initial flakiness stems from the fact that we update Global (User) setting, but when reading the setting value, if user has overridden the workspace setting, [it will take priority](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration).
The original requirements for [standalone mode](https://sonarsource.atlassian.net/browse/MMF-3726) state:
> Focus on new code should be defined globally in SonarLint setting and should be applied to all projects
The original requirements for [Connected mode](https://sonarsource.atlassian.net/browse/MMF-3244) are not clear, but I think it makes sense to apply the same policy for both.
[SLVSCODE-721]: …

SLVSCODE-721 change scope of focusOnNewCode setting

---

src/util/logging.ts

[SLVSCODE-1145](https://sonarsource.atlassian.net/browse/SLVSCODE-1145)
Part of SLVSCODE-1098
Adding this option enables nicer formatting of SonarQube for IDE output (they are considered as logs), and `SonarQube for IDE` also appears as one of the options for `Developer: Export Logs...` command.
[SLVSCODE-1145]: https://sonarsource.atlassian.net/browse/SLVSCODE-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-1145 Make sure SQ-IDE output is considered as extension logs

---

.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml
.github/workflows/credcheck.yml
.github/workflows/releasability.yml
.github/workflows/release.yml

[BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073)
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-8073 Migrate public repositories workflows to large runners

---

CHANGELOG.md
package.json

[SLVSCODE-1176](https://sonarsource.atlassian.net/browse/SLVSCODE-1176)
SLVSCODE-1176
[SLVSCODE-1176]: https://sonarsource.atlassian.net/browse/SLVSCODE-1176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-1176 Update Go analyzer 1.22.1 to 1.23.1, update LS for compatibility with Go Enterprise

---

CHANGELOG.md
src/extension.ts
src/findings/findingsTreeDataProvider.ts
src/newcode/newCodeDefinitionService.ts

[SLVSCODE-1268](https://sonarsource.atlassian.net/browse/SLVSCODE-1268)
This inconsistency has been there for a long time. It just became more visible now that we have a dedicated button/view to visualise new code focus as well. We could come up with a better long-term improvement later.
[SLVSCODE-1268]: https://sonarsource.atlassian.net/browse/SLVSCODE-1268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-1268 security findings view fixes

---

src/findings/findingsTreeDataProvider.ts
src/findings/findingsTreeDataProviderUtil.ts
test/suite/findingsTreeDataProvider/findingFilters.test.ts
test/suite/findingsTreeDataProvider/updateFindings.test.ts

[SLVSCODE-1296](https://sonarsource.atlassian.net/browse/SLVSCODE-1296)
The main issue was in the `FindingsFileNode` constructor where `vscode.workspace.getWorkspaceFolder(this.resourceUri)` could return `undefined`, but the code was still trying to pass it to `getRelativePathFromFullPath()` which expects a non-null workspace folder.
Fixes the issue:
[SLVSCODE-1296]: https://sonarsource.atlassian.net/browse/SLVSCODE-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVSCODE-1296 Avoid errors on files outside workspace

---

.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml
.github/workflows/credcheck.yml
.github/workflows/releasability.yml
.github/workflows/release.yml

[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …

BUILD-8875: Migrate to standardized GitHub runner names
