.gitignore, .travis.yml, .vscodeignore, gulpfile.js, package-lock.json, package.json, scripts/prepare.js, src/__tests__/util.test.ts, src/extension.ts, src/util.ts, tsconfig.json
See SLCORE-232 for the actual changes.
=> SLVSCODE-47 Enable issue tracking for sub folders and multi root workspaces

src/extension.ts
See https://github.com/microsoft/vscode-remote-release/issues/2023
=> SLVSCODE-101 Fix TypeScript compiler finder

package.json, scripts/prepare.js, src/extension.ts
Depends on https://github.com/SonarSource/sonarlint-language-server/pull/14
=> SLVSCODE-8 Cleaner SonarLint output

README.md
Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-vscode/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:
=> Readme marketing suggestions

scripts/prepare.js
=> SLVSCODE-127 update PHP analyzer version to 3.4

scripts/prepare.js
update python analyzer to 2.10
=> SLVSCODE-126 update python analyzer to 2.10

its/samples/sample-java-maven-multi-module/module-java/src/test/java/edu/marcelo/AppTest.java, its/src/test/javaSuite/java.test.ts, scripts/dependencies.json
=> SLVSCODE-129 update java analyzer version to 6.4

package.json, scripts/dependencies.json, src/extension.ts
Depends on https://github.com/SonarSource/sonarlint-language-server/pull/28
=> SLVSCODE-147 Support analysis of PLSQL in Oracle Developer Tools

scripts/dependencies.json
=> SLVSCODE-149 update PHP analyzer to 3.9.0

scripts/dependencies.json
=> SLVSCODE-150 update python analyzer to 3.1.0

package.json, src/commands.ts, src/extension.ts, src/protocol.ts
=> SLVSCODE-120 add protocol method to open sonarlint output

test/suite/locations.test.ts
Make sure tests are well isolated by closing all open documents between cases.
=> Stabilize locations UI test

CHANGELOG.md, package-lock.json, package.json, scripts/dependencies.json
Update sonarlint-core and sonar-python to released versions, reflect changes in changelog.
=> Prepare release 2.0

its/userdir/User/settings.json
https://code.visualstudio.com/docs/editor/workspace-trust
=> Skip workspace trust check in QA (1.57+)

src/commands.ts, src/extension.ts, src/protocol.ts
=> SLVSCODE-187 first secret detection notification

package-lock.json, package.json
=> Bump follow-redirects

CHANGELOG.md, scripts/dependencies.json
[SLVSCODE-290](https://jira.sonarsource.com/browse/SLVSCODE-290)
[SLVSCODE-291](https://jira.sonarsource.com/browse/SLVSCODE-291)
[SLVSCODE-293](https://jira.sonarsource.com/browse/SLVSCODE-293)
=> SLVSCODE v3.6 analyzer updates

src/connected/autobinding.ts
=> SLVSCODE-349 show list of all projects when multiple matches are found

its/src/test/runTest.ts
This reverts commit 367bf176e9942e7c569d69e0b27197a195dd42b0.
See https://github.com/microsoft/vscode/issues/166588
=> Re-enable Java QA on "insiders" axis

.github/actions/vsce-publish/package-lock.json, .github/actions/vsce-publish/package.json, package-lock.json, package.json
This change allows to publish targeted and universal VSIXes in the same version
=> SLVSCODE-332 update vsce version to 2.15

CHANGELOG.md, scripts/dependencies.json
update js/ts/css analyzer from 9.13 to 10.0.0
Notes from languages team:
- Support for JavaScript analysis inside HTML files
- Fixing false positives and false negatives
- Upgrading core dependencies
=> SLVSCODE-415 update js/ts/css analyzer from 9.13 to 10.0.0

scripts/dependencies.json, src/connected/autobinding.ts, src/connected/connectionsetup.ts, src/extension.ts, src/lsp/protocol.ts, test/suite/autobinding.test.ts
Update vscode to take advantage of [SonarLintCore Binding suggestions](https://github.com/SonarSource/sonarlint-core/blob/master/spec/binding_suggestion.adoc).
=> SLVSCODE-361 use auto binding algorithm from core

CHANGELOG.md, scripts/dependencies.json
Update java analyzer and changelog
=> Update Java analyzer, update changelog

scripts/dependencies.json, src/extension.ts
Update to the latest language server for pre-release validation
=> Update language server

.cirrus.yml
https://sonarsource.atlassian.net/browse/BUILD-3478
=> BUILD-3478 update dependency of mend and dogfood tasks

.cirrus.yml, CHANGELOG.md, package-lock.json, package.json
Make sure to simply review.
**DO NOT MERGE** if you are a reviewer and not a SonarLint team member
=> BUILD-3483 set cirrus clone depth to 50

.cirrus.yml
Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-vscode/blob/master/docs/contributing.md).
And please ensure your pull request adheres to the following guidelines:
=> BUILD-3485 Mend scans must use a version on 3 digits

scripts/dependencies.json, src/extension.ts, src/issue/issue.ts, src/issue/resolveIssue.ts, src/lsp/client.ts, src/lsp/protocol.ts, src/util/commands.ts, src/util/uri.ts
Add command which allows reopening all local-only issue for current file
=> Allow reopening local-only issues

.cirrus.yml, build-sonarlint/artifactory.mjs, build-sonarlint/jreDownload.mjs, build-sonarlint/omnisharpDownload.mjs, scripts/dependencies.json, scripts/prepare.mjs
This is an attempt at mitigating [BUILD-4326](https://sonarsource.atlassian.net/browse/BUILD-4326) while remaining friendly to community contributors.
[BUILD-4326]: https://sonarsource.atlassian.net/browse/BUILD-4326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BUILD-4326 Avoid depending on anonymous access to artifactory

src/commons.ts
The Clean Code attributes pages were recently improved in the Docs.
This PR updates the destination URL.
A redirect will be requested in the interim.
=> update new Clean Code landing URL

.github/workflows/release.yml
Should fix https://github.com/SonarSource/sonarlint-vscode/actions/runs/7723423704
=> BUILD-4326 add artifactory token to .npmrc in release action

.github/workflows/release.yml
=> SLVSCODE-714 fix typo in release action

package.json, scripts/dependencies.json, src/newcode/newCodeDefinitionService.ts
Updated settings clarifying the option for Focus on New Code, updated status bar tooltip for Focus on New Code.
=> SLVSCODE-771: Update UI for focus on New Code

scripts/dependencies.json, src/connected/connectionsetup.ts, src/lsp/client.ts, src/lsp/protocol.ts, src/settings/connectionsettings.ts, styles/connectionsetup.css, test/suite/connectionsetup.test.ts, webview-ui/connectionsetup.js
=> SLVSCODE-747 make organizationKey into a dropdown

CHANGELOG.md, scripts/dependencies.json
SLVSCODE-836
SLVSCODE-822
SLVSCODE-833
SLVSCODE-835
SLVSCODE-825
=> 4.10 analyzer updates; SLVSCODE-836 SLVSCODE-822 SLVSCODE-833 SLVSCODE-835 SLVSCODE-825

src/connected/assistCreatingConnection.ts, src/connected/connectionsetup.ts, src/extension.ts, src/help/constants.ts, src/lsp/protocol.ts
[SLVSCODE-841](https://sonarsource.atlassian.net/browse/SLVSCODE-841)
With a fix for the 🟥 quality gate 🙈 
[SLVSCODE-841]: https://sonarsource.atlassian.net/browse/SLVSCODE-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-841 Update server product comparison link

package-lock.json, package.json
[SLVSCODE-842](https://sonarsource.atlassian.net/browse/SLVSCODE-842)
[SLVSCODE-842]: https://sonarsource.atlassian.net/browse/SLVSCODE-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-842 Bump webpack version to 5.94.0

scripts/dependencies.json
[SLVSCODE-844](https://sonarsource.atlassian.net/browse/SLVSCODE-844)
[SLVSCODE-844]: https://sonarsource.atlassian.net/browse/SLVSCODE-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-844 Use release of SLLS 3.10

.github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, docs/PULL_REQUEST_TEMPLATE.md
=> SLVSCODE-853 Jira integration: Use repo vault token

test/suite/connectionsetup.test.ts
[SLVSCODE-859](https://sonarsource.atlassian.net/browse/SLVSCODE-859)
[SLVSCODE-859]: https://sonarsource.atlassian.net/browse/SLVSCODE-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-859 Slow down test to increase stability

scripts/dependencies.json
[SLVSCODE-868](https://sonarsource.atlassian.net/browse/SLVSCODE-868)
Part of [SLVSCODE-855](https://sonarsource.atlassian.net/browse/SLVSCODE-855)
[SLVSCODE-855]: https://sonarsource.atlassian.net/browse/SLVSCODE-855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-868]: https://sonarsource.atlassian.net/browse/SLVSCODE-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-868 Use latest Language Server

src/fixSuggestions/fixSuggestionsService.ts, src/issue/issue.ts, src/util/showMessage.ts, src/util/uri.ts
[SLVSCODE-666](https://sonarsource.atlassian.net/browse/SLVSCODE-666)
[SLVSCODE-666]: https://sonarsource.atlassian.net/browse/SLVSCODE-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-666 show notification when file is not found

src/connected/binding.ts
[SLVSCODE-882](https://sonarsource.atlassian.net/browse/SLVSCODE-882)
[SLVSCODE-882]: https://sonarsource.atlassian.net/browse/SLVSCODE-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-882 assistBinding overwrite old binding

CHANGELOG.md, scripts/dependencies.json
[SLVSCODE-902](https://sonarsource.atlassian.net/browse/SLVSCODE-902)
SLVSCODE-892
SLVSCODE-887
SLVSCODE-885
SLVSCODE-884
SLVSCODE-883
[SLVSCODE-902]: https://sonarsource.atlassian.net/browse/SLVSCODE-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-902 Analyzer updates 4.12

scripts/dependencies.json
[SLVSCODE-913](https://sonarsource.atlassian.net/browse/SLVSCODE-913)
[SLVSCODE-913]: https://sonarsource.atlassian.net/browse/SLVSCODE-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-913 Use latest Language Server

its/src/test/csharpsuite/csharp.test.ts, its/src/test/javaSuite/java.test.ts, scripts/dependencies.json, src/extension.ts, src/issue/issue.ts, src/lsp/client.ts, src/lsp/protocol.ts, src/lsp/server.ts, src/rules/rulepanel.ts, test/suite/rulepanel.test.ts
[SLVSCODE-889](https://sonarsource.atlassian.net/browse/SLVSCODE-889)
[SLVSCODE-889]: https://sonarsource.atlassian.net/browse/SLVSCODE-889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-889 getIssueDetails

THIRD-PARTY-NOTICES, scripts/dependencies.json, src/extension.ts
[SLVSCODE-879](https://sonarsource.atlassian.net/browse/SLVSCODE-879)
[SLVSCODE-879]: https://sonarsource.atlassian.net/browse/SLVSCODE-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-879 Support C# analyzer repackaging

src/connected/connectionsetup.ts
[SLVSCODE-922](https://sonarsource.atlassian.net/browse/SLVSCODE-922)
[SLVSCODE-922]: https://sonarsource.atlassian.net/browse/SLVSCODE-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-922 update smart notifications docs link SonarQube Cloud

package-lock.json, package.json, src/connected/autobinding.ts, src/extension.ts, src/util/commands.ts, test/suite/autobinding.test.ts
[SLVSCODE-930](https://sonarsource.atlassian.net/browse/SLVSCODE-930)
[SLVSCODE-930]: https://sonarsource.atlassian.net/browse/SLVSCODE-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-930 bring back the bind all workspace folders command

scripts/dependencies.json
=> SLVSCODE-936 Adapt to sonar-text repackaging

its/src/test/javaSuite/java.test.ts, src/extension.ts, src/fileSystem/fileSystemServiceImpl.ts, test/suite/autobinding.test.ts, test/suite/sharedConnectedModeSettings.test.ts
[SLVSCODE-873](https://sonarsource.atlassian.net/browse/SLVSCODE-873)
[SLVSCODE-873]: https://sonarsource.atlassian.net/browse/SLVSCODE-873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-873 crawl directory before listFilesInFolder is called

CHANGELOG.md, scripts/dependencies.json
[SLVSCODE-952](https://sonarsource.atlassian.net/browse/SLVSCODE-952)
[SLVSCODE-952]: https://sonarsource.atlassian.net/browse/SLVSCODE-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-952 java analyzer update

scripts/dependencies.json
[SLVSCODE-954](https://sonarsource.atlassian.net/browse/SLVSCODE-954)
Part of SLVSCODE-929
[SLVSCODE-954]: https://sonarsource.atlassian.net/browse/SLVSCODE-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-954 Use latest Language Server and Omnisharp

package-lock.json, package.json, scripts/dependencies.json
[SLVSCODE-961](https://sonarsource.atlassian.net/browse/SLVSCODE-961)
[SLVSCODE-961]: https://sonarsource.atlassian.net/browse/SLVSCODE-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-961 prepare release 4.13.2

package-lock.json, package.json, scripts/dependencies.json
[SLVSCODE-985](https://sonarsource.atlassian.net/browse/SLVSCODE-985)
[SLVSCODE-985]: https://sonarsource.atlassian.net/browse/SLVSCODE-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-985 bearer auth fix

src/connected/connectionsetup.ts
[SLVSCODE-978](https://sonarsource.atlassian.net/browse/SLVSCODE-978)
[SLVSCODE-978]: https://sonarsource.atlassian.net/browse/SLVSCODE-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-978 do not search user organizations with SonarQube Server

src/help/constants.ts
[SLVSCODE-989](https://sonarsource.atlassian.net/browse/SLVSCODE-989)
Part of SLVSCODE-967
[SLVSCODE-989]: https://sonarsource.atlassian.net/browse/SLVSCODE-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-989 Try deduplicate help&feedback constants

src/extension.ts
[SLVSCODE-958](https://sonarsource.atlassian.net/browse/SLVSCODE-958)
[SLVSCODE-958]: https://sonarsource.atlassian.net/browse/SLVSCODE-958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-958 avoid showing unnecessary error

scripts/dependencies.json, src/extension.ts
[SLVSCODE-846](https://sonarsource.atlassian.net/browse/SLVSCODE-846)
[SLVSCODE-846]: https://sonarsource.atlassian.net/browse/SLVSCODE-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-846 do not pollute additionalAttributes map

src/connected/connections.ts, test/suite/connections.test.ts
[SLVSCODE-746](https://sonarsource.atlassian.net/browse/SLVSCODE-746)
[SLVSCODE-746]: https://sonarsource.atlassian.net/browse/SLVSCODE-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-746 Use non trivial ID for first level nodes of connected mode view

src/connected/connectionsetup.ts
[DOC-1835](https://sonarsource.atlassian.net/browse/DOC-1835)
[DOC-1835]: https://sonarsource.atlassian.net/browse/DOC-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-1835 rebrand docs URL

package.json
[SLVSCODE-1022](https://sonarsource.atlassian.net/browse/SLVSCODE-1022)
SLVSCODE-1022
[SLVSCODE-1022]: https://sonarsource.atlassian.net/browse/SLVSCODE-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1022 Add action to empty "Locations" view for users to open the "Problems" view

CHANGELOG.md, package.json
[SLVSCODE-1024](https://sonarsource.atlassian.net/browse/SLVSCODE-1024)
SLVSCODE-1002
SLVSCODE-1011
SLVSCODE-1012
SLVSCODE-1013
SLVSCODE-1015
SLVSCODE-1018
[SLVSCODE-1024]: https://sonarsource.atlassian.net/browse/SLVSCODE-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1024 Update analyzers for 4.16

CHANGELOG.md, package.json
[SLVSCODE-1025](https://sonarsource.atlassian.net/browse/SLVSCODE-1025)
[SLVSCODE-1025]: https://sonarsource.atlassian.net/browse/SLVSCODE-1025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1025 Update JS/TS/CSS analyzer 10.20 to 10.21

package-lock.json, package.json
[SLVSCODE-1038](https://sonarsource.atlassian.net/browse/SLVSCODE-1038)
[SLVSCODE-1038]: https://sonarsource.atlassian.net/browse/SLVSCODE-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1038 Update dependencies that have false positives on SCA

package.json
[SLVSCODE-1040](https://sonarsource.atlassian.net/browse/SLVSCODE-1040)
Part of SLVSCODE-1027
[SLVSCODE-1040]: https://sonarsource.atlassian.net/browse/SLVSCODE-1040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1040 Use latest SLLS (git blaming improvements)

src/connected/connectionsetup.ts
[SLVSCODE-1041](https://sonarsource.atlassian.net/browse/SLVSCODE-1041)
[SLVSCODE-1041]: https://sonarsource.atlassian.net/browse/SLVSCODE-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1041 hide region selector instead of not creating it

CHANGELOG.md, package.json, src/cfamily/ondemand.ts, src/monitoring/monitoring.ts, test/suite/ondemand.test.ts
SLVSCODE-1049
SLVSCODE-1048
SLVSCODE-1047
SLVSCODE-1046
=> SLVSCODE-1049 SLVSCODE-1048 SLVSCODE-1047 SLVSCODE-1046 SLVSCODE-1055 SLVSCODE-1063 SLVSCODE-1064 4.17 analyzer updates

.github/workflows/PullRequestClosed.yml
[SLVSCODE-1068](https://sonarsource.atlassian.net/browse/SLVSCODE-1068)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SLVSCODE-1068]: https://sonarsource.atlassian.net/browse/SLVSCODE-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1068 Autoclose issues created by Jira integration

.gitignore
[SLVSCODE-1071](https://sonarsource.atlassian.net/browse/SLVSCODE-1071)
Part of SLVSCODE-1054
[SLVSCODE-1071]: https://sonarsource.atlassian.net/browse/SLVSCODE-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1071 Ignore .vscode/settings.json file

CHANGELOG.md, package.json
[SLVSCODE-1060](https://sonarsource.atlassian.net/browse/SLVSCODE-1060)
[SLVSCODE-1065](https://sonarsource.atlassian.net/browse/SLVSCODE-1065)
[SLVSCODE-1069](https://sonarsource.atlassian.net/browse/SLVSCODE-1069)
[SLVSCODE-1060]: https://sonarsource.atlassian.net/browse/SLVSCODE-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1065]: https://sonarsource.atlassian.net/browse/SLVSCODE-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1069]: https://sonarsource.atlassian.net/browse/SLVSCODE-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1060, SLVSCODE-1065, SLVSCODE-1069 Update analyzers for 4.18

CHANGELOG.md, package.json, src/connected/connectionsetup.ts
[SLVSCODE-1073](https://sonarsource.atlassian.net/browse/SLVSCODE-1073)
Part of SLVSCODE-1054
[SLVSCODE-1073]: https://sonarsource.atlassian.net/browse/SLVSCODE-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1073 Choose SonarQube Cloud region instead of instance

package.json, src/connected/connectionsetup.ts, styles/connectionsetup.css, webview-ui/connectionsetup.js, webview-ui/organizationsDropdownHelper.js
[SLVSCODE-1001](https://sonarsource.atlassian.net/browse/SLVSCODE-1001)
[SLVSCODE-1084](https://sonarsource.atlassian.net/browse/SLVSCODE-1084)
[SLVSCODE-1001]: https://sonarsource.atlassian.net/browse/SLVSCODE-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1084]: https://sonarsource.atlassian.net/browse/SLVSCODE-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1001, SLVSCODE-1084 Allow connection to public organizations

.cirrus.yml, package.json, src/extension.ts, src/monitoring/monitoring.ts
[SLVSCODE-1095](https://sonarsource.atlassian.net/browse/SLVSCODE-1095)
SLVSCODE-1095
[SLVSCODE-1095]: https://sonarsource.atlassian.net/browse/SLVSCODE-1095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1095 Send uncaught exceptions to monitoring

CHANGELOG.md, package.json
[SLVSCODE-1091](https://sonarsource.atlassian.net/browse/SLVSCODE-1091)
[SLVSCODE-1092](https://sonarsource.atlassian.net/browse/SLVSCODE-1092)
[SLVSCODE-1093](https://sonarsource.atlassian.net/browse/SLVSCODE-1093)
[SLVSCODE-1094](https://sonarsource.atlassian.net/browse/SLVSCODE-1094)
SLVSCODE-1091
SLVSCODE-1092
SLVSCODE-1093
SLVSCODE-1094
[SLVSCODE-1091]: https://sonarsource.atlassian.net/browse/SLVSCODE-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1092]: https://sonarsource.atlassian.net/browse/SLVSCODE-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1093]: https://sonarsource.atlassian.net/browse/SLVSCODE-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> SLVSCODE-1091, SLVSCODE-1092, SLVSCODE-1093, SLVSCODE-1094 Update analyzers for 4.19

package.json
[SLVSCODE-1104](https://sonarsource.atlassian.net/browse/SLVSCODE-1104)
Part of SLVSCODE-1103
[SLVSCODE-1104]: https://sonarsource.atlassian.net/browse/SLVSCODE-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1104 Prepare release 4.19

src/connected/binding.ts
[SLVSCODE-1096](https://sonarsource.atlassian.net/browse/SLVSCODE-1096)
[SLVSCODE-1096]: https://sonarsource.atlassian.net/browse/SLVSCODE-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1096 check for undefined before binding creation

package.json, src/extension.ts, src/fixSuggestions/fixSuggestionsService.ts, src/lsp/protocol.ts
[SLVSCODE-1109](https://sonarsource.atlassian.net/browse/SLVSCODE-1109)
[SLVSCODE-1109]: https://sonarsource.atlassian.net/browse/SLVSCODE-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1109 base changes for AI CodeFix

CHANGELOG.md, package.json
[SLVSCODE-1119](https://sonarsource.atlassian.net/browse/SLVSCODE-1119)
[SLVSCODE-1117](https://sonarsource.atlassian.net/browse/SLVSCODE-1117)
[SLVSCODE-1111](https://sonarsource.atlassian.net/browse/SLVSCODE-1111)
[SLVSCODE-1110](https://sonarsource.atlassian.net/browse/SLVSCODE-1110)
[SLVSCODE-1105](https://sonarsource.atlassian.net/browse/SLVSCODE-1105)
[SLVSCODE-1119]: https://sonarsource.atlassian.net/browse/SLVSCODE-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1117]: https://sonarsource.atlassian.net/browse/SLVSCODE-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1111]: https://sonarsource.atlassian.net/browse/SLVSCODE-1111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> SLVSCODE-1119 SLVSCODE-1117 SLVSCODE-1111 SLVSCODE-1110 SLVSCODE-1105 SLVSCODE-1118 4.20 analyzer updates

package.json
[SLVSCODE-1130](https://sonarsource.atlassian.net/browse/SLVSCODE-1130)
[SLVSCODE-1130]: https://sonarsource.atlassian.net/browse/SLVSCODE-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1130 Prepare bugfix release

package.json, src/connected/autobinding.ts, src/connected/connections.ts, src/connected/connectionsetup.ts, src/contextManager.ts, src/extension.ts, src/help/constants.ts, src/issue/issue.ts, src/rules/rules.ts, src/util/commands.ts, test/suite/helpAndFeedbackTreeDataProvider.test.ts
[SLVSCODE-1120](https://sonarsource.atlassian.net/browse/SLVSCODE-1120)
[SLVSCODE-1120]: https://sonarsource.atlassian.net/browse/SLVSCODE-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1120, SLVSCODE-1121, SLVSCODE-1122, SLVSCODE-1123, SLVSCODE-1124, SLVSCODE-1125, SLVSCODE-1126, SLVSCODE-1127 UX improvements

.github/workflows/release.yml
[SLVSCODE-643](https://sonarsource.atlassian.net/browse/SLVSCODE-643)
[SLVSCODE-643]: https://sonarsource.atlassian.net/browse/SLVSCODE-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-643 Upload artifacts to GitHub release automatically

build-sonarlint/common.mjs, build-sonarlint/populateBuildNumber.mjs, dogfood/package-lock.json, dogfood/package.json, dogfood/src/updatesService.ts, src/extension.ts, src/monitoring/monitoring.ts, src/util/util.ts
[SLVSCODE-1138](https://sonarsource.atlassian.net/browse/SLVSCODE-1138)
[SLVSCODE-1138]: https://sonarsource.atlassian.net/browse/SLVSCODE-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1138 fix dogfooding extension

dogfood/package-lock.json, dogfood/package.json, dogfood/src/modules.d.ts, dogfood/src/pluginInstallationService.ts
[SLVSCODE-1138](https://sonarsource.atlassian.net/browse/SLVSCODE-1138)
[SLVSCODE-1138]: https://sonarsource.atlassian.net/browse/SLVSCODE-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1138 fix progress reporting with dogfood extension

CHANGELOG.md, package.json
[SLVSCODE-1163](https://sonarsource.atlassian.net/browse/SLVSCODE-1163)
[SLVSCODE-1157](https://sonarsource.atlassian.net/browse/SLVSCODE-1157)
[SLVSCODE-1150](https://sonarsource.atlassian.net/browse/SLVSCODE-1150)
[SLVSCODE-1148](https://sonarsource.atlassian.net/browse/SLVSCODE-1148)
[SLVSCODE-1147](https://sonarsource.atlassian.net/browse/SLVSCODE-1147)
[SLVSCODE-1163]: https://sonarsource.atlassian.net/browse/SLVSCODE-1163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1157]: https://sonarsource.atlassian.net/browse/SLVSCODE-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1150]: https://sonarsource.atlassian.net/browse/SLVSCODE-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> SLVSCODE-1163, SLVSCODE-1157, SLVSCODE-1150, SLVSCODE-1148, SLVSCODE-1147 4.22 analyzer updates

src/extension.ts, src/settings/connectionsettings.ts
[SLVSCODE-1164](https://sonarsource.atlassian.net/browse/SLVSCODE-1164)
[SLVSCODE-1164]: https://sonarsource.atlassian.net/browse/SLVSCODE-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1164 allow storing token for two connections with the same org key

CHANGELOG.md, package.json
[SLVSCODE-1183](https://sonarsource.atlassian.net/browse/SLVSCODE-1183)
[SLVSCODE-1182](https://sonarsource.atlassian.net/browse/SLVSCODE-1182)
[SLVSCODE-1180](https://sonarsource.atlassian.net/browse/SLVSCODE-1180)
[SLVSCODE-1171](https://sonarsource.atlassian.net/browse/SLVSCODE-1171)
[SLVSCODE-1170](https://sonarsource.atlassian.net/browse/SLVSCODE-1170)
[SLVSCODE-1167](https://sonarsource.atlassian.net/browse/SLVSCODE-1167)
[SLVSCODE-1181](https://sonarsource.atlassian.net/browse/SLVSCODE-1181)
[SLVSCODE-1183]: https://sonarsource.atlassian.net/browse/SLVSCODE-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1182]: https://sonarsource.atlassian.net/browse/SLVSCODE-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> SLVSCODE-1183, SLVSCODE-1182, SLVSCODE-1180, SLVSCODE-1171, SLVSCODE-1170, SLVSCODE-1167, SLVSCODE-1181 Update analyzers for 4.23

CHANGELOG.md, package.json
[SLVSCODE-1186](https://sonarsource.atlassian.net/browse/SLVSCODE-1186)
[SLVSCODE-1186]: https://sonarsource.atlassian.net/browse/SLVSCODE-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1186 Update Text analyzer 2.23 to 2.24

README.md, package.json
[SLVSCODE-1187](https://sonarsource.atlassian.net/browse/SLVSCODE-1187)
[SLVSCODE-1187]: https://sonarsource.atlassian.net/browse/SLVSCODE-1187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1187 Update marketplace description and tags

package.json, src/cfamily/cfamily.ts, src/connected/binding.ts, src/connected/sharedConnectedModeSettingsService.ts, src/settings/connectionsettings.ts
[SLVSCODE-1166](https://sonarsource.atlassian.net/browse/SLVSCODE-1166)
[SLVSCODE-1166]: https://sonarsource.atlassian.net/browse/SLVSCODE-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1166 Remove redundant 'ask me later' options

src/extension.ts, src/lsp/protocol.ts
[SLVSCODE-1200](https://sonarsource.atlassian.net/browse/SLVSCODE-1200)
[SLVSCODE-1200]: https://sonarsource.atlassian.net/browse/SLVSCODE-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1200 don't show missing requirements notification if user said so

src/util/showMessage.ts
[SLVSCODE-1177](https://sonarsource.atlassian.net/browse/SLVSCODE-1177)
[SLVSCODE-1177]: https://sonarsource.atlassian.net/browse/SLVSCODE-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1177 make sure open in IDE errors are descriptive

src/findings/findingsTreeDataProvider.ts, src/languageModelTools/listPotentialSecurityIssuesTool.ts
[SLVSCODE-1239](https://sonarsource.atlassian.net/browse/SLVSCODE-1239)
[SLVSCODE-1239]: https://sonarsource.atlassian.net/browse/SLVSCODE-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1208 Adapt Language Model Tools to include taint vulnerabilities

CHANGELOG.md, package-lock.json, package.json
[SLVSCODE-1220](https://sonarsource.atlassian.net/browse/SLVSCODE-1220)
[SLVSCODE-1223](https://sonarsource.atlassian.net/browse/SLVSCODE-1223)
[SLVSCODE-1220]: https://sonarsource.atlassian.net/browse/SLVSCODE-1220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1223]: https://sonarsource.atlassian.net/browse/SLVSCODE-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1220, SLVSCODE-1223, SLVSCODE-1237 Analyzer updates for 4.25

package.json, src/extension.ts, src/findings/findingsTreeDataProvider.ts, src/issue/taintVulnerabilityDecorator.ts, src/util/bindingUtils.ts, src/util/commands.ts, src/util/issue.ts
[SLVSCODE-1205](https://sonarsource.atlassian.net/browse/SLVSCODE-1205)
[SLVSCODE-1205]: https://sonarsource.atlassian.net/browse/SLVSCODE-1205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1205 migrate taints to new view

package-lock.json, package.json
[SLVSCODE-1258](https://sonarsource.atlassian.net/browse/SLVSCODE-1258)
=> SLVSCODE-1258 Prepare iteration 4.26

CHANGELOG.md, package.json
[SLVSCODE-1253](https://sonarsource.atlassian.net/browse/SLVSCODE-1253)
[SLVSCODE-1267](https://sonarsource.atlassian.net/browse/SLVSCODE-1267)
SLVSCODE-1213
[SLVSCODE-1253]: https://sonarsource.atlassian.net/browse/SLVSCODE-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1267]: https://sonarsource.atlassian.net/browse/SLVSCODE-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1253, SLVSCODE-1267, SLVSCODE-1213 4.26 analyzer updates

src/connected/binding.ts, src/util/bindingUtils.ts, test/suite/bindingUtils.test.ts
[SLVSCODE-1260](https://sonarsource.atlassian.net/browse/SLVSCODE-1260)
[SLVSCODE-1260]: https://sonarsource.atlassian.net/browse/SLVSCODE-1260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1260 adjust dashboard URL based on SQC region

CHANGELOG.md, package.json
[SLVSCODE-1269](https://sonarsource.atlassian.net/browse/SLVSCODE-1269)
[SLVSCODE-1269]: https://sonarsource.atlassian.net/browse/SLVSCODE-1269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1269 Update JS/TS/CSS analyzer 10.24 to 11.0

package-lock.json, package.json
[SLVSCODE-1273](https://sonarsource.atlassian.net/browse/SLVSCODE-1273)
[SLVSCODE-1273]: https://sonarsource.atlassian.net/browse/SLVSCODE-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1273 Prepare next dev iteration

package-lock.json, package.json
[SLVSCODE-1291](https://sonarsource.atlassian.net/browse/SLVSCODE-1291)
[SLVSCODE-1291]: https://sonarsource.atlassian.net/browse/SLVSCODE-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1291 Prepare next dev iteration

src/commons.ts
[DOC-2267](https://sonarsource.atlassian.net/browse/DOC-2267)
[DOC-2267]: https://sonarsource.atlassian.net/browse/DOC-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2267 Update clean code link

CHANGELOG.md, package.json
[SLVSCODE-1286](https://sonarsource.atlassian.net/browse/SLVSCODE-1286)
[SLVSCODE-1289](https://sonarsource.atlassian.net/browse/SLVSCODE-1289)
[SLVSCODE-1294](https://sonarsource.atlassian.net/browse/SLVSCODE-1294)
[SLVSCODE-1295](https://sonarsource.atlassian.net/browse/SLVSCODE-1295)
[SLVSCODE-1298](https://sonarsource.atlassian.net/browse/SLVSCODE-1298)
[SLVSCODE-1299](https://sonarsource.atlassian.net/browse/SLVSCODE-1299)
[SLVSCODE-1300](https://sonarsource.atlassian.net/browse/SLVSCODE-1300)
[SLVSCODE-1301](https://sonarsource.atlassian.net/browse/SLVSCODE-1301)
[SLVSCODE-1286]: https://sonarsource.atlassian.net/browse/SLVSCODE-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVSCODE-1289]: …
=> SLVSCODE-1286 SLVSCODE-1289 SLVSCODE-1294 SLVSCODE-1295 SLVSCODE-1298 SLVSCODE-1299 SLVSCODE-1300 SLVSCODE-1301 4.28 analyzer updates

src/extension.ts, src/findings/findingTypes/dependencyRiskNode.ts, src/findings/findingTypes/findingNode.ts, src/findings/findingTypes/hotspotNode.ts, src/findings/findingTypes/notebookFindingNode.ts, src/findings/findingTypes/taintVulnerabilityNode.ts, src/findings/findingsFileNode.ts, src/findings/findingsFolderNode.ts, src/findings/findingsTreeDataProvider.ts, src/findings/findingsTreeDataProviderUtil.ts, src/findings/notebookNode.ts, src/hotspot/hotspots.ts, src/issue/resolveIssue.ts, src/issue/taintVulnerabilityDecorator.ts, src/languageModelTools/listPotentialSecurityIssuesTool.ts, test/suite/findingsTreeDataProvider/findingFilters.test.ts, test/suite/findingsTreeDataProvider/findingsTreeDataProviderUtil.test.ts, test/suite/findingsTreeDataProvider/showAllInfoForFinding.test.ts, test/suite/findingsTreeDataProvider/updateFindings.test.ts, test/suite/hotspots.test.ts
[SLVSCODE-1303](https://sonarsource.atlassian.net/browse/SLVSCODE-1303)
[SLVSCODE-1303]: https://sonarsource.atlassian.net/browse/SLVSCODE-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1303 clean up findingsTreeDataProvider

CHANGELOG.md, package.json
[SLVSCODE-1306](https://sonarsource.atlassian.net/browse/SLVSCODE-1306)
[SLVSCODE-1306]: https://sonarsource.atlassian.net/browse/SLVSCODE-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1306 js analyzer update

package.json, src/extension.ts
[SLVSCODE-1326](https://sonarsource.atlassian.net/browse/SLVSCODE-1326)
[SLVSCODE-1326]: https://sonarsource.atlassian.net/browse/SLVSCODE-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1326 stop publishing config change at startup

package.json
[SLVSCODE-1337](https://sonarsource.atlassian.net/browse/SLVSCODE-1337)
[SLVSCODE-1337]: https://sonarsource.atlassian.net/browse/SLVSCODE-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1337 Use latest SLLS

package-lock.json, package.json
[SLVSCODE-1342](https://sonarsource.atlassian.net/browse/SLVSCODE-1342)
[SLVSCODE-1342]: https://sonarsource.atlassian.net/browse/SLVSCODE-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1342 Prepare next dev iteration

package-lock.json, package.json
[SLVSCODE-1355](https://sonarsource.atlassian.net/browse/SLVSCODE-1355)
[SLVSCODE-1355]: https://sonarsource.atlassian.net/browse/SLVSCODE-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1355 Prepare next dev iteration

CHANGELOG.md, package.json
[SLVSCODE-1371](https://sonarsource.atlassian.net/browse/SLVSCODE-1371)
[SLVSCODE-1360](https://sonarsource.atlassian.net/browse/SLVSCODE-1360)
[SLVSCODE-1358](https://sonarsource.atlassian.net/browse/SLVSCODE-1358)
[SLVSCODE-1357](https://sonarsource.atlassian.net/browse/SLVSCODE-1357)
[SLVSCODE-1351](https://sonarsource.atlassian.net/browse/SLVSCODE-1351)
[SLVSCODE-1350](https://sonarsource.atlassian.net/browse/SLVSCODE-1350)
Part of 
Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-vscode/blob/master/docs/contributing.md).
And please ensure your pull request adheres to the following guidelines:
[SLVSCODE-1371]: https://sonarsource.atlassian.net/browse/SLVSCODE-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
=> SLVSCODE-1371, SLVSCODE-1360, SLVSCODE-1358, SLVSCODE-1357, SLVSCODE-1351, SLVSCODE-1350 analyzers updates

package.json
[SLVSCODE-1377](https://sonarsource.atlassian.net/browse/SLVSCODE-1377)
[SLVSCODE-1377]: https://sonarsource.atlassian.net/browse/SLVSCODE-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1377 Update language server

CHANGELOG.md, package.json, src/aiAgentsConfiguration/aiAgentRuleConfig.ts, src/aiAgentsConfiguration/aiAgentsConfigurationTreeDataProvider.ts, src/contextManager.ts, src/extension.ts, src/help/constants.ts, src/util/commands.ts, test/suite/aiAgentsConfiguration/aiAgentConfigurationTreeDataProvider.test.ts, test/suite/aiAgentsConfiguration/aiAgentRuleConfig.test.ts, test/suite/aiAgentsConfiguration/mcpServerConfig.test.ts
[SLVSCODE-1381](https://sonarsource.atlassian.net/browse/SLVSCODE-1381)
[SLVSCODE-1381]: https://sonarsource.atlassian.net/browse/SLVSCODE-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1381 delay MCP-related context initialization
